### ISSUE TITLE
Time sub-setting - improvement

### ISSUE THREAD

**Issue by vestlink** [ctmm-initiative/ctmm-webapp#30]
I was using the app with my data, and was missing the opportunity to be able to define a time-span (from date - to date), when in the time-subsetting pane.

Maybe two input fields in the "Current Time Range"?

**Comment by xhdong-umd** [comment]
So you feel it's easier to use a date picker instead of dragging on the histogram? Is it because the mouse selection is difficult to get specific dates? You can drag a range first, then move the range left and right, or only move one end a little bit.

Currently a lot of things will update when the mouse selection on histogram changed. Ideally I will want the selection on histogram to sync with date picker so the app will be consistent and the changes are minimal. However [Shiny doesn't support setting selection programmatically yet](https://github.com/rstudio/shiny/issues/1456).

If we still add the date picker, then we have two sources of truth for the date range. It's difficult to determine which one is the wanted input when both exist.

We can add a button for date picker, so clicking button will override the mouse selection. Though I'll need more manual management code to deal with all the corner cases. Previously this is all automatically handled by Shiny. Now I have to manually manage them when explicit override was introduced.

@chfleming Did you find it's easier to use a date picker?

**Comment by chfleming** [comment]
I think its very likely that some users will want to input specific dates (e.g., hunting season).

**Comment by xhdong-umd** [comment]
I added a manual date picker. After dates are selected, click the `set` button to apply. I didn't add hour/minutes because I guess date is enough.

<img width="699" alt="screen shot 2017-09-07 at 2 29 40 pm" src="https://user-images.githubusercontent.com/25039897/30179032-065ee97e-93d9-11e7-8bec-e6660c7109f2.png">
