### ISSUE TITLE
Error in shinyAppDir(x) : App dir must contain either app.R or server.R.

### ISSUE THREAD

**Issue by vestlink** [ctmm-initiative/ctmm-webapp#40]
source("https://raw.githubusercontent.com/ctmm-initiative/ctmm-webapp/master/inst/app/run.R")

produces:

Error in shinyAppDir(x) : App dir must contain either app.R or server.R.

Both on Windows and Mac (R version 3.4.2)

**Comment by xhdong-umd** [comment]
Sorry I didn't update this part. I'm in the process of converting the app into a package, which involved a lot of cumbersome work and introduced lots of changes. 

Ideally I should keep the github repo stable and only update it when everything is working. Because of the complexity of my git setup this was not done properly before.

I have updated the repo and shinyapps.io app, hopefully it will work as before. And I'll only update the github repo after most things work.

There was an error message in shinyapps.io said `rgeos` is missing when creating map. I've added it to the package dependency to solve this problem.
